---
title: "Assignment2_SOK1005"
format: html
editor: visual
---

```{r}
rm(list=ls()) 
#dowloading packages
library(tidyverse)
library(janitor)
library(lubridate)
library(zoo)
library("rvest")
```

```{r}
#scraping data from web usinge rvest
content <- read_html("https://www.motor.no/aktuelt/motors-store-vintertest-av-rekkevidde-pa-elbiler/217132")
tables <- content %>% html_table(fill = TRUE)
df_range <- tables[[1]]
df_range <- df_range[-1,] #removing unecesary row
```

```{r}
#changing names
df_range$X3 <- gsub("km", "", as.character(df_range$X3))
df_range <- df_range %>%
  rename(model=X1) %>% 
  rename(stop=X3) %>% 
  rename(wltp=X2) %>% 
  rename(deviation=X4) %>% 
  mutate(stop=as.numeric(stop))

#making wltp numeric
df_range[is.na(df_range)] <- 0
df_range$wltp <- gsub("km.*", "", as.character(df_range$wltp))
df_range<- df_range %>% 
  filter(stop != 0) %>% 
  mutate(wltp=as.numeric(wltp))

```

```{r}
#setting plot
df_range %>% 
  ggplot(aes(x=wltp, y=stop))+
  geom_point()+
  geom_abline(coef=c(0,1), col="dodgerblue", size=1, lwd=1)+
  labs(x="Wltp in km", y="stopp in km",
       title="Wltp range vs real life range on electric cars", subtitle = "Test resault on 31 diffrent cars")+
  xlim(250,600)+
  ylim(200,600)+
  theme_bw()
```

```{r}
#setting plot
df_range %>% 
  ggplot(aes(x=wltp, y=stop))+
  geom_point()+
  geom_abline(coef=c(0,1), col="dodgerblue", size=1, lwd=1)+
  geom_smooth(method=lm, se=FALSE, col="firebrick1")+
  labs(x="Wltp in km", y="stopp in km",
       title="Wltp range vs real life range on electric cars", subtitle = "Test resault on 31 diffrent cars")+
  xlim(250,600)+
  ylim(200,600)+
  theme_bw()
```
